# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shopify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopify
pod 'SDWebImage', '~> 5.0'
pod 'Kingfisher'
pod 'Braintree'
pod 'Braintree/PayPalNativeCheckout'
pod 'lottie-ios'

  target 'ShopifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopifyUITests' do
    # Pods for testing
  end

end
